title: AltDrag
url: https://stefansundin.github.io
baseurl: /altdrag
description: AltDrag brings the window moving behavior from Linux to Windows.
author: Stefan Sundin

# posts
permalink: /news/:year-:month-:day-:title.html

# build
gems: [jekyll-coffeescript]
markdown: kramdown
kramdown:
  input: GFM

# github data
# https://help.github.com/articles/repository-metadata-on-github-pages/
github:
  repository_nwo: stefansundin/altdrag
  repository_url: https://github.com/stefansundin/altdrag
  clone_url: https://github.com/stefansundin/altdrag.git
  releases_url: https://github.com/stefansundin/altdrag/releases
  issues_url: https://github.com/stefansundin/altdrag/issues
